import Head from "next/head";
// import axios from "axios";

export default function BlogPage() {
  // const getData = async () => {
  //   return await axios
  //     .get("https://broad-accidental-servant.glitch.me/posts", {})
  //     .then(({ data }) => {
  //       setPosts(data);
  //     })
  //     .catch((error) => {
  //       console.error(error.message);
  //     });
  // };

  return (
    <>
      <Head>
        <title>Maria-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
