import Head from "next/head";
import { useState } from "react";
import { Clip } from "../modules/Clip/Clip";
import { Blog } from "../modules/Blog/Blog";
import { useIsLogin } from "../hooks/useIs";
import { useIsLogged } from "../hooks/useIs";

export default function HomePage() {

  const isLogin = useIsLogin();
  const isLogged = useIsLogged();

  return (
    <>
      <Head>
        <title>Maria-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header
        isLogged={isLogged}
        setIsLogin={setIsLogin}
        setIsLogged={setIsLogged}
      /> */}
      <Clip />
      <Blog {...isLogin} {...isLogged} />
    </>
  );
}
