import Head from "next/head";
import { Clip } from "../modules/Clip/Clip";
import { Blog } from "../modules/Blog/Blog";
import { useIsLogin } from "../hooks/useIs";
import { useIsLogged } from "../hooks/useIs";

export default function HomePage() {

  const isLogin = useIsLogin();
  const isLogged = useIsLogged();

  return (
    <>
      <Head>
        <title>Maria Gonza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons-medium.png" />
      </Head>
      <Clip />
      <Blog {...isLogin} {...isLogged} />
    </>
  );
}
