import Head from "next/head";
import { Clip } from "../modules/Clip/Clip";
import { Blog } from "../modules/Blog/Blog";

export default function HomePage() {

  return (
    <>
      <Head>
        <title>Maria-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header
        isLogged={isLogged}
        setIsLogin={setIsLogin}
        setIsLogged={setIsLogged}
      /> */}
      <Clip />
      <Blog />
    </>
  );
}
